template_path: jenkinsapplication.yaml

parameters:
  AssociatePublicIpAddress: "false"
  VolumeType: "gp2"
  VolumeSize: "15"
  AmazonLinux: !ami_resolver {{ stack_group_config.region }}
  InstanceType: "m4.large"
  Public1Subnet: !stack_output prod/vpc.yaml::Public1Subnet
  Public2Subnet: !stack_output prod/vpc.yaml::Public2Subnet
  Private1Subnet: !stack_output prod/vpc.yaml::Private1Subnet
  Private2Subnet: !stack_output prod/vpc.yaml::Private2Subnet
  VpcId: !stack_output prod/vpc.yaml::VpcId
  DesiredCapacity: "1"
  MaxSize: "1"
  MinSize: "1"
  JenkinsInstancePort: "8080"
  LoadBalancerPort: "443"
  LoadBalancerProtocol: "HTTPS"
  LoadBalancerInsecurePort: "80"
  LoadBalancerInsecureProtocol: "HTTP"
  JenkinsInstanceProfile: !stack_output prod/iamroles.yaml::JenkinsInstanceProfileArn
  JenkinsElasticFileSystem: !stack_output prod/efs.yaml::JenkinsElasticFileSystem
  HostedZoneName: {{ var.hostedzonename | default("esn.crlabs.cloud") }}
  JenkinsSG: !stack_output prod/securitygroups.yaml::JenkinsSG
  JenkinsELBSG: !stack_output prod/securitygroups.yaml::JenkinsELBSG
  Type: "CNAME"
  TTL: "60"
  LoadBalancerType: "application"
  LoadBalancerScheme: "internet-facing"
  HealthCheckEnabled: "true"
  HealthCheckIntervalSeconds: "30"
  HealthCheckPath: "/login"
  HealthCheckPort: "8080"
  HealthCheckProtocol: "HTTP"
  HealthCheckTimeoutSeconds: "3"
  HealthyThresholdCount: "2"
  TargetType: "instance"
  ProjectCode: {{ stack_group_config.project_code }}
  Env: {{ command_path.0 }}
