template_path: vpc.yaml

parameters:
  CidrBlock: 10.0.0.0/16
  EnableDnsSupport: "true"
  EnableDnsHostnames: "true"
  Az1: {{ stack_group_config.region }}a
  Az2: {{ stack_group_config.region }}b
  Az1PublicCidr: 10.0.1.0/24
  Az2PublicCidr: 10.0.2.0/24
  Az1PrivateCidr: 10.0.3.0/24
  Az2PrivateCidr: 10.0.4.0/24
  MapPublicIpOnLaunch: "false"
  EIPDomain: "vpc"
  Env: {{ command_path.0 }}
  ProjectCode: {{ stack_group_config.project_code }}
