---
Parameters:
  AssociatePublicIpAddress:
    Type: String
  VolumeType:
    Type: String
  VolumeSize:
    Type: String
  AmazonLinux:
    Type: String
  InstanceType:
    Type: String
  Private1Subnet:
    Type: String
  Private2Subnet:
    Type: String
  Public1Subnet:
    Type: String
  Public2Subnet:
    Type: String
  VpcId:
    Type: String
  DesiredCapacity:
    Type: String
  MaxSize:
    Type: String
  MinSize:
    Type: String
  JenkinsInstancePort:
    Type: String
  LoadBalancerPort:
    Type: String
  JenkinsInstanceProfile:
    Type: String
  ProjectCode:
    Type: String
  Env:
    Type: String
  HostedZoneName:
    Type: String
  TTL:
    Type: Number
  Type:
    Type: String
  JenkinsSG:
    Type: String
  JenkinsELBSG:
    Type: String
  LoadBalancerProtocol:
    Type: String
  JenkinsElasticFileSystem:
    Type: String
  LoadBalancerInsecurePort:
    Type: String
  LoadBalancerInsecureProtocol:
    Type: String
  LoadBalancerType:
    Type: String
  LoadBalancerScheme:
    Type: String
  HealthCheckEnabled:
    Type: String
  HealthCheckIntervalSeconds:
    Type: String
  HealthCheckPath:
    Type: String
  HealthCheckPort:
    Type: String
  HealthCheckProtocol:
    Type: String
  HealthCheckTimeoutSeconds:
    Type: String
  HealthyThresholdCount:
    Type: String
  TargetType:
    Type: String

Resources:

  JenkinsLC:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      AWS::CloudFormation::Init:
        config:
          commands:
            a:
              command: "sudo yum update -y"
            b:
              command: "sudo yum install -y java-1.8.0"
            c:
              command: "mkdir -p /var/lib/jenkins"
            d:
              command: "yum install amazon-efs-utils -y"
            e:
              command: !Join
                - ''
                - - 'mount -t efs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport '
                  - !Ref JenkinsElasticFileSystem
                  - ':/ /var/lib/jenkins'
            f:
              command: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo"
            g:
              command: "rpm --import http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key"
            h:
              command: "yum install jenkins -y"
            i:
              command: "service jenkins start"
            j:
              command: "chkconfig jenkins on"
            k:
              command:
                !Join
                  - ''
                  - - 'echo "aws ssm put-parameter --name "jenkins-init-password" --type "SecureString" '
                    - '--value file:///var/lib/jenkins/secrets/initialAdminPassword --key-id alias/aws/ssm --overwrite --region '
                    - !Ref 'AWS::Region'
                    - ' > /root/allout.txt 2>&1" | at now + 2 minutes'
    Properties:
      AssociatePublicIpAddress: !Ref AssociatePublicIpAddress
      ImageId: !Ref AmazonLinux
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref JenkinsSG
      IamInstanceProfile: !Ref JenkinsInstanceProfile
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -ex
          yum update aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -s ${AWS::StackName} -r JenkinsLC --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource JenkinsASG --region ${AWS::Region}

  JenkinsASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: JenkinsASG
      DesiredCapacity: !Ref DesiredCapacity
      LaunchConfigurationName: !Ref JenkinsLC
      MaxSize: !Ref MaxSize
      MinSize: !Ref MinSize
      LoadBalancerNames:
        - !Ref JenkinsELB
      VPCZoneIdentifier:
        - !Ref Private1Subnet
        - !Ref Private2Subnet
    CreationPolicy:
      AutoScalingCreationPolicy:
        MinSuccessfulInstancesPercent: 100
      ResourceSignal:
        Count: !Ref DesiredCapacity

  JenkinsELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join
        - ''
        - - !Ref ProjectCode
          - '-'
          - !Ref Env
          - 'application-loadbalancer'
      Scheme: !Ref LoadBalancerType
      Type: !Ref LoadBalancerScheme
      SecurityGroups:
        - !Ref JenkinsELBSG
      Subnets:
        - !Ref Public1Subnet
        - !Ref Public2Subnet

  JenkinsELBHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - !Ref JenkinsCertificate
      LoadBalancerArn: !Ref JenkinsELB
      Port: !Ref LoadBalancerPort
      Protocol: !Ref LoadBalancerProtocol
      DefaultActions:
        - TargetGroupArn: !Ref JenkinsTargetGroup
          Type: "forward"

  JenkinsELBHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref JenkinsELB
      Port: !Ref LoadBalancerInsecurePort
      Protocol: !Ref LoadBalancerInsecureProtocol
      DefaultActions:
        - Type: "redirect"
          RedirectConfig:
            - Host: "#{host}"
              Path: "#{path}"
              Port: !Ref LoadBalancerPort
              Protocol: !Ref LoadBalancerProtocol
              Query: "#{query}"
              StatusCode: "HTTP_301"

  JenkinsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: !Ref HealthCheckEnabled
      HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckPort: !Ref HealthCheckPort
      HealthCheckProtocol: !Ref HealthCheckProtocol
      HealthCheckTimeoutSeconds: !Ref HealthCheckTimeoutSeconds
      HealthyThresholdCount: !Ref HealthyThresholdCount
      Name: !Join
        - ''
        - - !Ref ProjectCode
          - '-'
          - !Ref Env
          - '-target-group'
      Port: !Ref JenkinsInstancePort
      Protocol: !Ref HealthCheckProtocol
      TargetType: !Ref TargetType
      VpcId: !Ref VpcId

  MyHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: "My own hosted zone"
      Name: !Ref HostedZoneName

  JenkinsRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref MyHostedZone
      ResourceRecords:
        - !GetAtt JenkinsELB.DNSName
      Name: !Join
        - ''
        - - !Ref ProjectCode
          - '.'
          - !Ref HostedZoneName
      TTL: !Ref TTL
      Type: !Ref Type

  JenkinsCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join
        - ''
        - - !Ref ProjectCode
          - '.'
          - !Ref HostedZoneName
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref ProjectCode
              - '-'
              - !Ref Env
              - '-'
              - 'jenkins-certificate'
